added date3Label attribute to store netTerm for invoice
peakflo/invoice-pdf-generator pull request #16
Opened 2022-11-11 13:42 UTC by santo-peakflo

## Description
added date3Label attribute to store netTerm for invoice
## Notion Link
https://www.notion.so/peakflo/Add-calculated-net-term-to-invoice-pdf-dueDate-IssueDate-1-3dd1b31fd7b840ca84d175e112988f16

2022-11-11 16:22 UTC, nabid-pf approved these changes

2022-11-11 17:01 UTC, dimavedenyapin requested changes

2022-11-11 17:01 UTC, dimavedenyapin commented on src/index.js
> +      date3: props.data?.date3 || "",
why is it called a `date` ?

2022-11-11 17:01 UTC, dimavedenyapin commented on src/index.js
> +    if(param.data?.data3 || param.data?.date3Label){
why here is `data3` and not `date3` ?

2022-11-11 17:01 UTC, dimavedenyapin commented on src/index.js
> +      date3: props.data?.date3 || "",
if it's a net term

2022-11-17 09:51 UTC, dimavedenyapin approved these changes

2022-11-17 12:06 UTC, merged